#!/bin/sh
test -f xrforge.com || {
  wget "https://codeberg.org/coderofsalvation/xrforge-v2/releases/download/0.2/xrforge-x86_64.com" -O xrforge.com
  chmod +x xrforge.com
}


set -x # show what's begin done in CI pipelines (codeberg/github e.g.)

# generate via xrforge and override some settings
# TIP: run 'xrforge.com admin' and add the generated 'xrforge.lua' config to this repo

./xrforge.com generate                                                   \
  baseurl=/$(basename $(pwd))/                                           \
  plugin_global_title='demo website'                                     \
  plugin_global_subtitle='generated by xrforge, served via a codeforge'  
