name: Publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v7
      - run: |
        ./generate.sh
      - if: ${{ forgejo.event_name == 'push' && forgejo.event.ref == 'refs/heads/main' }}
        uses: actions/git-pages@v2
        with:
          site: https://${{ forgejo.event.repository.owner.username }}.codeberg.page/${{ forgejo.event.repository.name }}/
          token: ${{ forgejo.token }}
          source: www/
